title: "Android Blogs"
author: "Faraz Ahmed"
description: "Faraz Ahmed"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}

footer:
  name             : "Shabaz Ahmed"
  avatar           : "WhatsApp Image 2021-06-24 at 7.01.19 PM.jpeg"
  bio              : "Daily learner, serial hacker, Dreamer!"
  location         : "Bengaluru"
  email            : "shabaz1729@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:shabaz1729@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/shabazahmed"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/build3r"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/shabazahmed_"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://build3r.github.io"

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:farazahmedfeb@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/FarazAhmedFeb1998"}
  - {title: Github, icon: linkedin, url: "https://www.linkedin.com/in/faraaz-ahmed-0a3a3816b"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
